/**
 * @file flight_computer.h
 * @brief Flight Computer Finite State Machine (FSM) definitions
 * @author Tomas Teixeira
 * @date October 2025
 *
 * This file defines the core flight computer state machine, including:
 * - FSM states and substates
 * - Flight profiles and parameters
 * - Command and event structures for inter-thread communication
 * - Boot status tracking
 *
 * @section fsm_overview FSM Overview
 * The flight computer operates as a state machine with the following main states:
 * - BOOT: System initialization
 * - IDLE: Waiting for configuration
 * - CONFIGED: Profile loaded, ready to arm
 * - ARMED: Ready for launch/test
 * - TEST_STAND: Static test mode
 * - FLIGHT: Active flight mode
 * - ABORT: Emergency abort sequence
 * - SAFE: Safe/recovery mode
 *
 * @see flight_computer_thread.c for implementation
 */

#ifndef FLIGHT_COMPUTER_FLIGHT_COMPUTER_H_
#define FLIGHT_COMPUTER_FLIGHT_COMPUTER_H_

#include "defs.h"
#include "FreeRTOS.h"
#include "queue.h"
#include <stdbool.h>
#include <stdint.h>
#include "Sensors/MS5607/MS5607.h"

/**
 * @defgroup FSM Flight Computer State Machine
 * @brief Core state machine definitions and functions
 * @{
 */

/**
 * @brief Main FSM states
 *
 * The flight computer progresses through these states during operation.
 * Transitions are triggered by commands, events, or internal conditions.
 */
typedef enum {
    STATE_BOOT = 0,     /**< System booting, initializing sensors and threads */
    STATE_IDLE,         /**< Idle state, waiting for profile configuration */
    STATE_CONFIGED,     /**< Profile configured, ready to arm */
    STATE_ARMED,        /**< Armed and ready for launch or test */
    STATE_TEST_STAND,   /**< Test stand mode for static testing (legacy, replaced by STATE_TEST_<KIND> in Phase 3-A) */
    STATE_FLIGHT,       /**< Active flight mode with guidance */
    STATE_ABORT,        /**< Emergency abort sequence active */
    STATE_SAFE,         /**< Safe/recovery mode, motors disabled */
    /* Phase 2 — per-test parent states. Each has its own sub-FSM defined
     * by SUB_TEST_* below; dispatch goes via test_kind_table[] in test_runner.h. */
    STATE_TEST_STATIC,      /**< Static thrust test active (parent state, see SUB_TEST_*) */
    STATE_TEST_TORQUE,      /**< Torque test active */
    STATE_TEST_TORQUE_CAL,  /**< Torque-calibration test (with servo sweep) */
    STATE_TEST_GUTTER,      /**< Vertical-rail tracking test (closed-loop) */
} fsm_state_t;

/**
 * @brief FSM sub-states for detailed state tracking
 *
 * Sub-states provide finer granularity within main states,
 * particularly for TEST_STAND and FLIGHT sequences.
 */
typedef enum {
    SUB_NONE = 0,               /**< No sub-state (default) */
    /* TEST_STAND sub-states */
    SUB_TS_SENSOR_CHECK,        /**< Checking sensors before test */
    SUB_TS_THROTTLE_RAMP,       /**< Throttle ramp in progress */
    /* FLIGHT sub-states */
    SUB_FL_IGNITION,            /**< Motor ignition sequence */
    SUB_FL_LIFTOFF_DETECT,      /**< Waiting for liftoff detection */
    SUB_FL_ASCENT,              /**< Powered ascent phase */
    SUB_FL_COAST,               /**< Unpowered coast phase */
    SUB_FL_DESCENT_BRAKE,       /**< Descent with braking */
    SUB_FL_LANDING_FLARE,       /**< Final landing flare */
    SUB_FL_TOUCHDOWN,           /**< Touchdown detected */
    SUB_FL_RECOVERY,            /**< Post-landing recovery */
    /* ARM sub-states */
    SUB_ARM_MOTOR_INIT,         /**< Initializing motor/ESC */
    SUB_ARM_MOTOR_CALIBRATING,  /**< ESC calibration in progress */
    SUB_ARM_READY,              /**< Armed and ready */
    /* Phase 2 — sub-states shared by every STATE_TEST_<KIND>. The parent
     * state distinguishes which test type; the sub-state tracks lifecycle. */
    SUB_TEST_CONFIGED,          /**< Profile loaded, hardware reachable */
    SUB_TEST_ARMED,             /**< Load cell tared, ESC armed, awaiting RUN */
    SUB_TEST_COUNTDOWN,         /**< 3..2..1..0 sequence broadcasted to GS */
    SUB_TEST_RUNNING,           /**< Motor live, on_run_tick driving actuators */
    SUB_TEST_HOLD,              /**< Manual-mode pause: motor at 0, test still live */
    SUB_TEST_FINISHING,         /**< Decelerating, flushing samples */
    SUB_TEST_DONE,              /**< Completed normally */
    SUB_TEST_ABORTED            /**< Aborted: heartbeat timeout, abort cmd, fault */
} fsm_substate_t;

/**
 * @brief Flight profile types
 *
 * Profiles define the operational mode and parameters for a mission.
 */
typedef enum {
    PROFILE_NONE = 0,           /**< No profile selected */
    PROFILE_GUTTER_RAMP = 1,    /**< Test stand: throttle ramp profile */
    PROFILE_GUTTER_HOLD = 2,    /**< Test stand: constant throttle hold */
    PROFILE_FLIGHT_PARAM = 3    /**< Flight mode: parametric (target altitude, auto-land) */
} flight_profile_t;

/**
 * @brief Internal FSM events (estimator → FSM)
 *
 * These events are generated by the estimator thread based on
 * flight conditions and sent to the FSM for state transitions.
 */
typedef enum {
    FSM_EVT_NONE = 0,           /**< No event */
    FSM_EVT_LIFTOFF,            /**< Liftoff detected (accel > threshold) */
    FSM_EVT_APOGEE,             /**< Apogee reached (velocity ≈ 0) */
    FSM_EVT_DESCENT_START,      /**< Descent phase started */
    FSM_EVT_FLARE_ALT,          /**< Flare altitude reached */
    FSM_EVT_TOUCHDOWN,          /**< Touchdown detected */
    FSM_EVT_LANDED,             /**< Stable landing confirmed */
    FSM_EVT_ALTITUDE_LIMIT,     /**< Max altitude limit reached */
    FSM_EVT_VELOCITY_LIMIT,     /**< Max velocity limit reached */
    FSM_EVT_MOTOR_ARMED,        /**< Motor arm sequence complete */
    FSM_EVT_CALIBRATION_DONE    /**< Sensor calibration complete */
} fsm_internal_event_t;

/**
 * @brief Flight profile parameters
 *
 * Contains all configurable parameters for a flight or test profile.
 * Parameters vary depending on profile type.
 */
typedef struct {
    flight_profile_t type;      /**< Profile type */

    /* Common parameters */
    float target_altitude_m;    /**< Target altitude for flight profiles (meters) */
    float flare_altitude_m;     /**< Altitude to begin landing flare (meters) */
    float touchdown_velocity_ms;/**< Target touchdown velocity (m/s) */
    float max_altitude_m;       /**< Maximum allowed altitude (safety limit) */
    float max_velocity_ms;      /**< Maximum allowed velocity (safety limit) */

    /* Gutter Hold specific */
    float hold_throttle;        /**< Constant throttle value (0.0-1.0) */

    /* Gutter Ramp specific */
    float ramp_duration_s;      /**< Duration of throttle ramp (seconds) */

    /* Safety limits */
    float throttle_min;         /**< Minimum throttle (typically 0.0) */
    float throttle_max;         /**< Maximum throttle (typically 1.0) */

    /* Landing zone (FLIGHT_PARAM profile) */
    float landing_lat;          /**< Landing zone latitude (degrees) */
    float landing_lon;          /**< Landing zone longitude (degrees) */
} profile_params_t;

/**
 * @brief Boot status tracking structure
 *
 * Tracks initialization status of all system components during boot.
 * Values: -1=not checked, 0=failed, 1=success
 */
typedef struct {
    /* Sensor initialization status */
    int8_t imu_init;            /**< IMU (ASM330LHHX) init status */
    int8_t baro_init;           /**< Barometer (MS5607) init status */
    int8_t mag_init;            /**< Magnetometer (MMC5983MA) init status */
    int8_t bno_init;            /**< 9-DOF IMU (BNO055) init status */
    int8_t gps_init;            /**< GPS (U-Blox) init status */
    int8_t sd_card_init;        /**< SD card init status */
    int8_t radio_init;          /**< Radio (E22 LoRa) init status */
    int8_t data_handler_init;   /**< Data handler init status */

    /* Sensor configuration status */
    int8_t imu_config;          /**< IMU configuration status */
    int8_t baro_config;         /**< Barometer configuration status */
    int8_t mag_config;          /**< Magnetometer configuration status */
    int8_t bno_config;          /**< BNO055 configuration status */
    int8_t gps_config;          /**< GPS configuration status */

    /* Thread startup status */
    int8_t sensors_thread_started;      /**< Sensors thread started */
    int8_t data_handler_thread_started; /**< Data handler thread started */
    int8_t telemetry_thread_started;    /**< Telemetry thread started */
    int8_t radio_thread_started;        /**< Radio thread started */
    int8_t sd_card_thread_started;      /**< SD card thread started */
    int8_t estimator_thread_started;    /**< Estimator thread started */
    int8_t controller_thread_started;   /**< Controller thread started */

    /* Summary counters */
    uint8_t total_checks;       /**< Total number of checks performed */
    uint8_t passed_checks;      /**< Number of passed checks */
    uint8_t failed_checks;      /**< Number of failed checks */
    uint8_t critical_failures;  /**< Number of critical failures (blocks operation) */
} boot_status_t;

/**
 * @brief Motor/ESC arm status
 *
 * Tracks ESC initialization and calibration state.
 */
typedef struct {
    bool esc_initialized;       /**< ESC has been initialized */
    bool calibration_done;      /**< ESC min/max calibration complete */
    float min_throttle;         /**< Calibrated minimum throttle */
    float max_throttle;         /**< Calibrated maximum throttle */
    uint32_t arm_timestamp;     /**< Timestamp when motor was armed */
} motor_arm_status_t;

/**
 * @brief Ping/Pong tracking for latency measurement
 *
 * Tracks ping requests and calculates round-trip time (RTT).
 */
typedef struct {
    uint8_t pending_seq;        /**< Sequence number of pending ping */
    uint32_t send_timestamp;    /**< FC timestamp when ping was sent */
    uint32_t gs_send_timestamp; /**< GS timestamp from ping command */
    bool awaiting_pong;         /**< Waiting for pong response */
    uint32_t last_rtt_ms;       /**< Last measured round-trip time (ms) */
} ping_tracker_t;

/** @brief Maximum number of boot errors to track */
#define BOOT_REPORT_MAX_ERRORS 8
/** @brief Maximum length of boot error message */
#define BOOT_ERROR_MSG_LEN     16

/**
 * @brief Boot report structure (sent to GS via telemetry)
 *
 * Packed structure sent as event payload to report boot status.
 */
typedef struct __attribute__((packed)) {
    uint8_t total_checks;       /**< Total boot checks performed */
    uint8_t passed;             /**< Checks that passed */
    uint8_t failed;             /**< Checks that failed */
    uint8_t critical;           /**< Critical failures */
    uint32_t boot_time_ms;      /**< Time to complete boot (ms) */
    char errors[BOOT_REPORT_MAX_ERRORS][BOOT_ERROR_MSG_LEN]; /**< Error messages */
    uint8_t error_count;        /**< Number of errors recorded */
} boot_report_t;

/**
 * @brief FSM runtime flags (bitfield)
 *
 * Compact storage for boolean runtime status flags.
 */
typedef struct {
    uint8_t baro_calibrated : 1;    /**< Barometer has been calibrated */
    uint8_t gps_locked : 1;         /**< GPS has a valid fix */
    uint8_t sensors_healthy : 1;    /**< All sensors reporting normally */
    uint8_t sd_logging_enabled : 1; /**< SD card logging is active */
    uint8_t estimator_running : 1;  /**< Estimator thread is running */
    uint8_t controller_running : 1; /**< Controller thread is running */
    uint8_t abort_requested : 1;    /**< Abort has been requested */
    uint8_t motor_armed : 1;        /**< Motor is armed */
} fsm_flags_t;

/**
 * @brief FSM Context - main flight computer state structure
 *
 * This is the central data structure for the flight computer,
 * containing all state, configuration, and runtime data.
 *
 * @note This structure is global (fsm_ctx) and accessed by multiple threads.
 *       Use fsm_get_state() and fsm_set_state() for thread-safe access.
 */
typedef struct {
    /* Current state */
    fsm_state_t state;              /**< Current FSM state */
    fsm_substate_t substate;        /**< Current sub-state */
    fsm_state_t prev_state;         /**< Previous state (for transitions) */
    fsm_substate_t prev_substate;   /**< Previous sub-state */

    /* Profile configuration */
    profile_params_t profile;       /**< Active flight profile parameters */

    /* Real-time navigation data (updated by estimator) */
    float altitude_agl_m;           /**< Current altitude above ground (meters) */
    float velocity_vertical_ms;     /**< Vertical velocity (m/s, positive=up) */
    float max_altitude_reached_m;   /**< Maximum altitude reached in flight */

    /* Timing */
    uint32_t state_entry_tick;      /**< Tick when current state was entered */
    uint32_t flight_start_tick;     /**< Tick when flight/test started */
    uint32_t boot_start_tick;       /**< Tick when boot started */

    /* Command tracking */
    uint8_t last_cmd_seq;           /**< Sequence number of last command */
    uint8_t last_cmd_status;        /**< Status of last command (0=OK) */

    /* Boot status */
    boot_status_t boot_status;      /**< Detailed boot status */

    /* Runtime flags */
    fsm_flags_t flags;              /**< Boolean runtime flags */

    /* Calibration data */
    baro_calibration_t baro_cal;    /**< Barometer calibration data */

    /* Motor status */
    motor_arm_status_t motor_status;/**< Motor/ESC arm status */

    /* Ping tracking */
    ping_tracker_t ping;            /**< Ping/pong latency tracking */

} fsm_ctx_t;

/**
 * @defgroup Commands Ground Station Commands
 * @brief Commands sent from Ground Station to Flight Computer
 * @{
 */

/**
 * @brief Command types (GS → FC)
 *
 * Commands are sent from the ground station and queued for
 * processing by the FSM thread.
 */
typedef enum {
    CMD_NONE = 0,           /**< No command / invalid */
    CMD_PING,               /**< Ping request for latency measurement */
    CMD_SET_PROFILE,        /**< Set flight profile (payload: profile type + params) */
    CMD_SET_PARAM,          /**< Set individual parameter */
    CMD_ARM,                /**< Arm the flight computer */
    CMD_DISARM,             /**< Disarm the flight computer */
    CMD_START_TEST,         /**< Start test sequence */
    CMD_LAUNCH,             /**< Initiate launch sequence */
    CMD_ABORT,              /**< Abort current operation */
    CMD_FORCE_SAFE,         /**< Force transition to SAFE state */
    CMD_CALIBRATE_BARO,     /**< Calibrate barometer (set ground reference) */
    CMD_CALIBRATE_MOTOR,    /**< ESC min/max throttle calibration */
    CMD_STATIC_TEST,        /**< (Legacy) Static thrust test fast-path; superseded by CMD_SET_TEST_PROFILE */
    CMD_RESYNC,             /**< Force TDMA resynchronization */
    CMD_SET_TEST_PROFILE,   /**< Phase 3-A: load a profile_t for the new test FSM (kind in byte 0) */
    CMD_HOLD,               /**< Phase 3-A: pause manual test (RUNNING → HOLD) */
    CMD_RESUME,             /**< Phase 3-A: resume manual test (HOLD → RUNNING) */
    CMD_STOP_TEST,          /**< Phase 3-A: graceful end (RUNNING → FINISHING → DONE) */
} fsm_command_t;

/** @} */ /* End of Commands group */

/**
 * @defgroup Events Telemetry Events
 * @brief Events sent from Flight Computer to Ground Station
 * @{
 */

/**
 * @brief Telemetry event types (FC → GS)
 *
 * Events are sent as telemetry packets to notify the ground station
 * of state changes, faults, and other significant occurrences.
 */
typedef enum {
    EVT_STATE_CHANGE = 0,       /**< FSM state changed */
    EVT_FAULT,                  /**< Fault detected */
    EVT_ABORT_TRIGGERED,        /**< Abort sequence initiated */
    EVT_PROFILE_LOADED,         /**< Flight profile loaded */
    EVT_CHECKS_GREEN,           /**< All pre-flight checks passed */
    EVT_CHECKS_RED,             /**< Pre-flight checks failed */
    EVT_BOOT_REPORT,            /**< Boot sequence report */
    EVT_ARMED,                  /**< System armed */
    EVT_DISARMED,               /**< System disarmed */
    EVT_LIFTOFF,                /**< Liftoff detected */
    EVT_APOGEE,                 /**< Apogee reached */
    EVT_LANDING,                /**< Landing detected */
    EVT_GENERIC_MSG,            /**< Generic text message */
    EVT_PONG,                   /**< Response to PING with RTT */
    EVT_BARO_CALIBRATED,        /**< Barometer calibration complete */
    EVT_MOTOR_ARMED,            /**< Motor arm sequence complete */
    EVT_MOTOR_CAL_STARTED,      /**< ESC calibration started (sending MAX) */
    EVT_MOTOR_CAL_PHASE2,       /**< ESC calibration phase 2 (sending MIN) */
    EVT_MOTOR_CALIBRATED,       /**< ESC calibration complete */
    EVT_STATIC_TEST_STARTED,    /**< Static thrust test started */
    EVT_STATIC_TEST_PROGRESS,   /**< Static test progress update */
    EVT_STATIC_TEST_COMPLETE,   /**< Static test completed successfully */
    EVT_STATIC_TEST_FAILED,     /**< Static test failed */
    EVT_THREAD_STAT,            /**< One task's runtime stats (round-robin, see thread_stat_payload_t) */
    EVT_SYSTEM_STAT,            /**< Global system stats: heap, uptime, etc (see system_stat_payload_t) */
    EVT_TEST_COUNTDOWN          /**< Phase 3-A (A6): countdown 3·2·1·0 during SUB_TEST_COUNTDOWN. Payload: 1 byte = seconds remaining */
} telemetry_event_type_t;

/** @} */ /* End of Events group */

/**
 * @brief Pong payload (for EVT_PONG event)
 */
typedef struct __attribute__((packed)) {
    uint8_t ping_seq;           /**< Echo of ping sequence number */
    uint32_t fc_timestamp;      /**< FC timestamp when ping was received */
    uint32_t rtt_ms;            /**< Round-trip time in milliseconds */
} pong_payload_t;

/**
 * @brief Calibration complete payload (for EVT_BARO_CALIBRATED)
 */
typedef struct __attribute__((packed)) {
    float reference_pressure;   /**< Reference pressure (mbar) */
    float temperature;          /**< Temperature at calibration (Celsius) */
    uint8_t samples;            /**< Number of samples averaged */
} calibration_payload_t;

/**
 * @brief Thread stats payload (for EVT_THREAD_STAT)
 *
 * One of these is emitted per task per round-robin tick (~1/s) so the
 * Ground Station can build the full table over a few superframes without
 * exceeding the event payload size.
 *
 * @note Must fit in telemetry_event_t.payload (24 bytes). Currently 22 bytes.
 */
typedef struct __attribute__((packed)) {
    uint8_t  task_idx;          /**< Index of this task within the round-robin (0..total-1) */
    uint8_t  total_tasks;       /**< Total task count this iteration */
    uint8_t  priority;          /**< FreeRTOS priority */
    uint8_t  state;             /**< eTaskState: 0=Running, 1=Ready, 2=Blocked, 3=Suspended, 4=Deleted */
    uint16_t stack_high_water;  /**< Min stack words remaining since boot (lower = closer to overflow) */
    uint32_t runtime_counter;   /**< Raw runtime counter (relative — divide by total to get %) */
    char     name[12];          /**< Task name, NUL-terminated where possible */
    uint16_t reserved;          /**< Padding/reserved for future use */
} thread_stat_payload_t;        /* 22 bytes */

/**
 * @brief Global system stats payload (for EVT_SYSTEM_STAT)
 *
 * Emitted once per round-robin cycle (~every 8s) so the GS can show heap
 * health, uptime, and a denominator for accurate per-task CPU percentages.
 */
typedef struct __attribute__((packed)) {
    uint32_t uptime_ms;             /**< HAL_GetTick() at emission */
    uint32_t free_heap_bytes;       /**< xPortGetFreeHeapSize() */
    uint32_t min_ever_free_heap;    /**< xPortGetMinimumEverFreeHeapSize() */
    uint32_t total_runtime;         /**< Sum of all per-task runtime counters at this snapshot */
    uint16_t task_count;            /**< Number of tasks currently in the system */
    uint16_t reserved;              /**< Reserved for future use */
} system_stat_payload_t;            /* 18 bytes */

/**
 * @brief Command message structure (radio_thread → fsm_thread)
 *
 * Commands received from GS are packaged in this structure
 * and sent to the FSM thread via queue.
 */
typedef struct {
    fsm_command_t cmd;          /**< Command type */
    uint8_t cmd_seq;            /**< Command sequence number */
    uint32_t gs_timestamp;      /**< GS timestamp when command was sent */
    union {
        struct __attribute__((packed)) {
            uint8_t profile_type;   /**< Profile type for SET_PROFILE */
            float param1;           /**< First parameter */
            float param2;           /**< Second parameter */
        } profile;
        float target_altitude;      /**< Target altitude for flight */
        uint8_t raw[32];            /**< Raw payload bytes (Phase 3-A: 16→32 to fit gutter profile) */
    } payload;                  /**< Command-specific payload */
} fsm_cmd_msg_t;

/**
 * @brief Event message structure (estimator_thread → fsm_thread)
 *
 * Internal events from the estimator are sent to the FSM
 * via this structure.
 */
typedef struct {
    fsm_internal_event_t type;  /**< Event type */
    uint32_t timestamp;         /**< Event timestamp */
    union {
        float altitude;         /**< Altitude value */
        float velocity;         /**< Velocity value */
        uint8_t raw[8];         /**< Raw data bytes */
    } data;                     /**< Event-specific data */
} fsm_event_msg_t;

/**
 * @brief State change event payload
 */
typedef struct __attribute__((packed)) {
    uint8_t old_state;          /**< Previous state */
    uint8_t old_substate;       /**< Previous sub-state */
    uint8_t new_state;          /**< New state */
    uint8_t new_substate;       /**< New sub-state */
    uint8_t reason;             /**< Reason code for transition */
} event_state_change_t;

/**
 * @brief Fault event payload
 */
typedef struct __attribute__((packed)) {
    uint16_t code;              /**< Fault code */
    char desc[32];              /**< Fault description string */
} event_fault_t;

/* ============================================================================
 * FreeRTOS Queues
 * ============================================================================ */

/** @brief Command queue (radio_thread → fsm_thread) */
extern QueueHandle_t queue_cmd_to_fsm;
/** @brief Event queue (estimator_thread → fsm_thread) */
extern QueueHandle_t queue_event_to_fsm;

/* ============================================================================
 * Global Context
 * ============================================================================ */

/** @brief Global FSM context (access via fsm_get_state/fsm_set_state) */
extern fsm_ctx_t fsm_ctx;

/* ============================================================================
 * Function Prototypes
 * ============================================================================ */

/**
 * @defgroup FSMFunctions FSM Functions
 * @brief FSM control and query functions
 * @{
 */

/**
 * @brief Initialize the flight computer FSM
 *
 * Initializes FSM context, creates queues, and sets initial state to BOOT.
 * Must be called before starting the FSM thread.
 */
void fsm_init(void);

/**
 * @brief Get current FSM state (thread-safe)
 * @return Current fsm_state_t value
 */
fsm_state_t fsm_get_state(void);

/**
 * @brief Get current FSM sub-state (thread-safe)
 * @return Current fsm_substate_t value
 */
fsm_substate_t fsm_get_substate(void);

/**
 * @brief Set FSM state (thread-safe)
 * @param state New state to set
 */
void fsm_set_state(fsm_state_t state);

/**
 * @brief Set FSM sub-state (thread-safe)
 * @param substate New sub-state to set
 */
void fsm_set_substate(fsm_substate_t substate);

/**
 * @brief Report component initialization status during boot
 * @param component Component name (e.g., "IMU", "BARO")
 * @param success true if init succeeded, false if failed
 */
void fsm_report_init_status(const char *component, bool success);

/**
 * @brief Report that a thread has started
 * @param thread_name Thread name (e.g., "SENSORS", "RADIO")
 */
void fsm_report_thread_started(const char *thread_name);

/**
 * @brief Check if boot sequence is complete
 * @return true if all boot checks are done
 */
bool fsm_is_boot_complete(void);

/**
 * @brief Check if data should be queued to estimator
 * @return true if estimator should receive data
 */
bool fsm_should_queue_to_estimator(void);

/**
 * @brief Check if data should be queued to SD card
 * @return true if SD logging is enabled
 */
bool fsm_should_queue_to_sd(void);

/**
 * @brief Check if logging is enabled
 * @return true if SD card logging is active
 */
bool fsm_is_logging_enabled(void);

/**
 * @brief Check if barometer is calibrated
 * @return true if barometer calibration is complete
 */
bool fsm_is_baro_calibrated(void);

/**
 * @brief Check if a barometer calibration is currently in progress.
 * Used by sensors_thread to suspend its periodic baro read so FC-thread
 * calibration samples don't race for the SPI bus.
 */
bool fsm_is_baro_calibrating(void);

/**
 * @brief Get barometer calibration data
 * @return Pointer to calibration structure, or NULL if not calibrated
 */
const baro_calibration_t* fsm_get_baro_calibration(void);

/**
 * @brief Send a command to the FSM (for internal use)
 * @param cmd Command type
 * @param cmd_seq Sequence number
 * @param payload Command payload (can be NULL)
 * @param size Payload size in bytes
 * @return true if command was queued successfully
 */
bool fsm_send_command(fsm_command_t cmd, uint8_t cmd_seq, const void *payload, uint16_t size);

/**
 * @brief Send an internal event to the FSM
 * @param event_type Event type
 * @param data Event data (can be NULL)
 * @return true if event was queued successfully
 */
bool fsm_send_event(fsm_internal_event_t event_type, const void *data);

/**
 * @brief Convert FSM state to string
 * @param state State value
 * @return String representation (e.g., "IDLE", "ARMED")
 */
const char* fsm_state_to_str(fsm_state_t state);

/**
 * @brief Convert FSM sub-state to string
 * @param substate Sub-state value
 * @return String representation
 */
const char* fsm_substate_to_str(fsm_substate_t substate);

/**
 * @brief Convert profile type to string
 * @param profile Profile type
 * @return String representation (e.g., "GUTTER_RAMP")
 */
const char* fsm_profile_to_str(flight_profile_t profile);

/** @} */ /* End of FSMFunctions group */

/** @} */ /* End of FSM group */

#endif /* FLIGHT_COMPUTER_FLIGHT_COMPUTER_H_ */
